### ISSUE TITLE
Implement `ksonnet init`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#80]
The `ksonnet init` command is specified in the [`ksonnet.next` design doc from August 2017](https://docs.google.com/document/d/19ZODMIismlurLdUC8sc8lBGgo6rcZGodL-CDgSjeJLE/edit?usp=sharing).

Implementing this specification implies the following work items:

- [x] **Completed in #88.** Update help documentation.
- [x] **Completed in #88.** Making `ksonnet-lib`'s `ksonnet-gen` package ready for consumption as a library.
    1. `ksonnet-gen` was written to be a command line tool rather than a library, so in several places it calls (_e.g._) `log.Fatal` in places `kubecfg` might not expect. We should remove these and return errors on failure instead.
    1. `ksonnet-gen` will add the SHA of the git revision that the Kubernetes codebase was at when we build from a `swagger.json` file. In this setting, this is not necessary, and most OpenAPI files won't be in a git repository anyway.
- [x] **Completed in #88.** `govendor`'ing a dependency on `ksonnet-lib`'s `ksonnet-gen` package. (`govendor` allows you to vendor only the parts of the library you depend on.)
- [x] **Completed in #88.** Add `init` to `cmd/`. This involves:
    1. Parsing the `init` flag if present
    1. Retrieving the schema (_e.g._, from network, from disk, from server)
    1. Generating `ksonnet-lib` code for the default environment, inside the `vendor/` directory.

**Comment by hausdorff** [comment]
I'm moving the "support generating from more than 1 kubernetes build" subpoint to feature complete. See #118.
