### ISSUE TITLE
Bring `ksonnet update` into sync with `ksonnet.next` spec

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#81]
The behavior of the `ksonnet update` command is specified in the [`ksonnet.next` design doc from August 2017](https://docs.google.com/document/d/19ZODMIismlurLdUC8sc8lBGgo6rcZGodL-CDgSjeJLE/edit?usp=sharing).

Bringing the command to specification implies the following work items:

- [x] **Completed in #88.** Update help documentation.
- [x] Decide on the name. The community seems to believe `apply` is clearer, so it seems like this is probably the leading contender.
  - [x] **Completed in #105.** Change `update` to `apply`. Deprecate `update`. Keep for two release cycles.
- [x] **Completed in #88.** Change `update` to:
    1. Expand and apply everything in the `components/` directory, if the `--env` flag is passed.
    2. Do the same thing it currently does if the `--file` flag is passed.

**Comment by hausdorff** [comment]
Update, we've decided on the name. It will be `apply`. But we're going to land the `prototype` changes first. The plan is:

* Mark `update` as deprecated.
* Keep it for 2 minor releases.
* Transition to `apply`.
